name: CI/CD Pipeline

on:
  push:
    branches: ['main']
  # pull_request:
  #   branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    with: node-version: 16.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn ci

      - name: Format and Lint
        uses: actions/setup-node@v3
      - run: yarn format:check
      - run: yarn lint
      - run: yarn tsc:check

      - name: Run Tests
        uses: actions/setup-node@v3
      - run: yarn test
