name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out Repository
      - uses: actions/checkout@v3

      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn ci

      - name: Format and Lint
        run: |
          yarn format:check
          yarn lint
          yarn tsc:check

      - name: Run Tests
        run: yarn test
